name: Attach Artifact to Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LPM version to release'
        required: true

jobs:
  attach-to-release:
    name: Attach Artifact to Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install upx
        run: |
          sudo apt-get update
          sudo apt-get install upx

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Setup GO environment
        run: |
          go mod download

      - name: Build
        run: make build

      - name: Get latest draft release ID
        id: get-release
        run: |
          LATEST_DRAFT_RELEASE=$(curl -X GET -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" | jq -r 'if .[].draft == true then .[].id else empty end')
          echo "Latest Draft Release ID: $LATEST_DRAFT_RELEASE"
          echo "RELEASE_ID=$LATEST_DRAFT_RELEASE" >> $GITHUB_ENV
